# fly.toml app configuration file generated for ytdlpapi on 2025-05-22T09:18:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ytdlpapi'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
